# Copyright 2018 Villa Labs All Rights Reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
version: '2'

networks:
  sampleNetwork:

volumes:
  ca.org1.villalabs.co:
  ca.org2.villalabs.co:
  orderer.villalabs.co:
  peer0.org1.villalabs.co:
  couchdb.peer0.org1.villalabs.co:
  peer1.org1.villalabs.co:
  couchdb.peer1.org1.villalabs.co:
  peer0.org2.villalabs.co:
  couchdb.peer0.org2.villalabs.co:
  peer1.org2.villalabs.co:
  couchdb.peer1.org2.villalabs.co:

services:
  ca.org1.villalabs.co:
    container_name: ca.org1.villalabs.co
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.villalabs.co
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.villalabs.co-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/42215d11328cb5dcc2054e4b4652a4174de4bb10e77e593d371a8a178da365a0_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org1.villalabs.co/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - sampleNetwork
  
  ca.org2.villalabs.co:
    container_name: ca.org2.villalabs.co
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org2.villalabs.co
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.villalabs.co-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/42215d11328cb5dcc2054e4b4652a4174de4bb10e77e593d371a8a178da365a0_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org2.villalabs.co/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - sampleNetwork

  orderer.villalabs.co:
    container_name: orderer.villalabs.co
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
      - ./channel-artifacts/:/etc/hyperledger/configtx
      - ./crypto-config/ordererOrganizations/villalabs.co/orderers/orderer.villalabs.co/:/etc/hyperledger/msp/orderer
      - ./crypto-config/peerOrganizations/org1.villalabs.co/peers/peer0.org1.villalabs.co/:/etc/hyperledger/msp/peerOrg1
    networks:
      - sampleNetwork

  peer0.org1.villalabs.co:
    container_name: peer0.org1.villalabs.co
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.villalabs.co
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.org1.villalabs.co:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_sampleNetwork
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.org1.villalabs.co:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer0.org1
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.villalabs.co/peers/peer0.org1.villalabs.co/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/org1.villalabs.co/users:/etc/hyperledger/msp/users
      - ./channel-artifacts:/etc/hyperledger/configtx
    depends_on:
      - orderer.villalabs.co
      - couchdb.peer0.org1.villalabs.co
    networks:
      - sampleNetwork
  
  peer1.org1.villalabs.co:
    container_name: peer1.org1.villalabs.co
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org1.villalabs.co
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer1.org1.villalabs.co:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_sampleNetwork
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer1.org1.villalabs.co:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer1.org1
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.villalabs.co/peers/peer0.org1.villalabs.co/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/org1.villalabs.co/users:/etc/hyperledger/msp/users
      - ./channel-artifacts:/etc/hyperledger/configtx
    depends_on:
      - orderer.villalabs.co
      - couchdb.peer1.org1.villalabs.co
    networks:
      - sampleNetwork

  peer0.org2.villalabs.co:
    container_name: peer0.org2.villalabs.co
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org2.villalabs.co
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.org2.villalabs.co:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_sampleNetwork
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.org2.villalabs.co:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer0.org2
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.villalabs.co/peers/peer0.org2.villalabs.co/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/org2.villalabs.co/users:/etc/hyperledger/msp/users
      - ./channel-artifacts:/etc/hyperledger/configtx
    depends_on:
      - orderer.villalabs.co
      - couchdb.peer0.org2.villalabs.co
    networks:
      - sampleNetwork
  
  peer1.org2.villalabs.co:
    container_name: peer1.org2.villalabs.co
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org2.villalabs.co
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer1.org2.villalabs.co:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_sampleNetwork
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer1.org2.villalabs.co:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer1.org2
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 10051:7051
      - 10053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.villalabs.co/peers/peer1.org2.villalabs.co/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/org2.villalabs.co/users:/etc/hyperledger/msp/users
      - ./channel-artifacts:/etc/hyperledger/configtx
    depends_on:
      - orderer.villalabs.co
      - couchdb.peer1.org2.villalabs.co
    networks:
      - sampleNetwork
      
  couchdb.peer0.org1.villalabs.co:
    container_name: couchdb.peer0.org1.villalabs.co
    environment:
      - COUCHDB_USER=peer0.org1
      - COUCHDB_PASSWORD=password
    image: hyperledger/fabric-couchdb
    ports:
      - 5984:5984
    networks:
      - sampleNetwork

  couchdb.peer1.org1.villalabs.co:
    container_name: couchdb.peer1.org1.villalabs.co
    environment:
      - COUCHDB_USER=peer1.org1
      - COUCHDB_PASSWORD=password
    image: hyperledger/fabric-couchdb
    ports:
      - 6984:5984
    networks:
      - sampleNetwork

  couchdb.peer0.org2.villalabs.co:
    container_name: couchdb.peer0.org2.villalabs.co
    environment:
      - COUCHDB_USER=peer0.org2
      - COUCHDB_PASSWORD=password
    image: hyperledger/fabric-couchdb
    ports:
      - 7984:5984
    networks:
      - sampleNetwork

  couchdb.peer1.org2.villalabs.co:
    container_name: couchdb.peer1.org2.villalabs.co
    environment:
      - COUCHDB_USER=peer1.org2
      - COUCHDB_PASSWORD=password
    image: hyperledger/fabric-couchdb
    ports:
      - 8984:5984
    networks:
      - sampleNetwork
  
  kafkaA.villalabs.co:
    container_name: kafkaA.villalabs.co
    image: hyperledger/fabric-kafka
    restart: always
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0.villalabs.co:2181, zookeeper1.villalabs.co:2181,zookeeper2.villalabs.co:2181
      - KAFKA_BROKER_ID=0
    ports:
      - 9092:9092
      - 9093:9093
    networks:
      - sampleNetwork
    depends_on:
      - zookeeper0.villalabs.co
      - zookeeper1.villalabs.co
      - zookeeper2.villalabs.co

  kafkaB.villalabs.co:
    container_name: kafkaB.villalabs.co
    image: hyperledger/fabric-kafka
    restart: always
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0.villalabs.co:2181, zookeeper1.villalabs.co:2181,zookeeper2.villalabs.co:2181
      - KAFKA_BROKER_ID=1
    ports:
      - 10092:9092
      - 10093:9093
    networks:
      - sampleNetwork
    depends_on:
      - zookeeper0.villalabs.co
      - zookeeper1.villalabs.co
      - zookeeper2.villalabs.co
      
  zookeeper0.villalabs.co:
    container_name: zookeeper0.villalabs.co
    image: hyperledger/fabric-zookeeper
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0.villalabs.co:2888:3888 server.2=zookeeper1.villalabs.co:2888:3888 server.3=zookeeper2.villalabs.co:2888:3888
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - sampleNetwork

  zookeeper1.villalabs.co:
    container_name: zookeeper1.villalabs.co
    image: hyperledger/fabric-zookeeper
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper0.villalabs.co:2888:3888 server.2=zookeeper1.villalabs.co:2888:3888 server.3=zookeeper2.villalabs.co:2888:3888
    ports:
      - 12181:2181
      - 12888:2888
      - 13888:3888
    networks:
      - sampleNetwork
  
  zookeeper2.villalabs.co:
    container_name: zookeeper2.villalabs.co
    image: hyperledger/fabric-zookeeper
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0.villalabs.co:2888:3888 server.2=zookeeper1.villalabs.co:2888:3888 server.3=zookeeper2.villalabs.co:2888:3888
    ports:
      - 22181:2181
      - 22888:2888
      - 23888:3888
    networks:
      - sampleNetwork

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.villalabs.co:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.villalabs.co/users/Admin@org1.villalabs.co/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../fabric-samples/chaincode/:/opt/gopath/src/github.com/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/config/
    networks:
        - sampleNetwork
   #depends_on:
   #   - orderer.villalabs.co
   #   - peer0.org1.villalabs.co
