# 
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: villalabs.co    
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Provider
  # ---------------------------------------------------------------------------
  - Name: Provider
    Domain: provider.villalabs.co
    EnableNodeOUs: true
    
    Template:
      Count: 2
       
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Consumer
  # ---------------------------------------------------------------------------
  - Name: Consumer
    Domain: consumer.villalabs.co
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
 