# 
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: sampledomain.com    
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Provider
  # ---------------------------------------------------------------------------
  - Name: Provider
    Domain: provider.sampledomain.com
    EnableNodeOUs: true
    
    Template:
      Count: 2
       
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Consumer
  # ---------------------------------------------------------------------------
  - Name: Consumer
    Domain: consumer.sampledomain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
 